import { VideoItem } from "@/lib/types";

export const INITIAL_VIDEOS: VideoItem[] = [
  {
    id: "1",
    title: "LLM時代のAIプロダクト設計",
    youtubeUrl: "https://youtube.com/watch?v=example1",
    thumbnailUrl: "https://picsum.photos/seed/ai/640/360",
    tags: ["AI", "LLM", "Product"],
    category: "AI",
    rating: 5,
    addedDate: "2023-11-01T10:00:00Z",
    publishDate: "2024-01-01T00:00:00Z",
    goodPoints: "### ポイント\n- ユースケース分解の考え方が学べる\n- AI機能の価値検証フローが具体的",
    memo: "次の企画で活用したい。",
  },
  {
    id: "2",
    title: "React 2024 完全ガイド",
    youtubeUrl: "https://youtube.com/watch?v=example2",
    thumbnailUrl: "https://picsum.photos/seed/react/640/360",
    tags: ["React", "TypeScript", "Frontend"],
    category: "プログラミング",
    rating: 4,
    addedDate: "2023-10-25T15:00:00Z",
    publishDate: "2023-12-15T00:00:00Z",
    goodPoints: "### 学習内容\n- 新しいHooksの使い道\n- パフォーマンス最適化のコツ",
    memo: "週末にハンズオンを行う。",
  },
  {
    id: "3",
    title: "Linuxパフォーマンスチューニング入門",
    youtubeUrl: "https://youtube.com/watch?v=example3",
    thumbnailUrl: "https://picsum.photos/seed/linux/640/360",
    tags: ["Linux", "Ops", "Performance"],
    category: "Linux",
    rating: 5,
    addedDate: "2023-11-10T08:30:00Z",
    publishDate: "2024-02-01T00:00:00Z",
    goodPoints: "### 感想\n- ボトルネックの見つけ方が整理されている\n- 実運用の視点が多い",
    memo: "監視の改善とセットで見直す。",
  },
  {
    id: "4",
    title: "CI/CD パイプライン構築の勘所",
    youtubeUrl: "https://youtube.com/watch?v=example4",
    thumbnailUrl: "https://picsum.photos/seed/cicd/640/360",
    tags: ["CI/CD", "DevOps", "Automation"],
    category: "CI/CD",
    rating: 3,
    addedDate: "2023-09-01T12:00:00Z",
    publishDate: "2023-10-01T00:00:00Z",
    goodPoints: "### コツ\n- パイプラインを小さく分割する\n- 失敗時のロールバック戦略",
    memo: "チームのテンプレに反映する。",
  },
];
